Attempt to get tests running.  They don't work for me, even before my changes.
`npm test carbon-components-react` fails because flatpickr isn't installed:

Error: /Users/bill/oss/DefinitelyTyped/types/carbon-components-react/lib/components/DatePicker/DatePicker.d.ts:1:47
ERROR: 1:47  expect  TypeScript@4.8 compile error:
Cannot find module 'flatpickr/dist/types/options' or its corresponding type declarations.

However, when I install it I just get other errors:

Error: /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/instance.d.ts:1:1
ERROR: 1:1  no-outside-dependencies  File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/instance.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md

/Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/locale.d.ts:1:1
ERROR: 1:1  no-outside-dependencies  File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/locale.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md

/Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/options.d.ts:1:1
ERROR: 1:1  no-outside-dependencies  File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/types/options.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md

/Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/utils/formatting.d.ts:1:1
ERROR: 1:1  no-outside-dependencies  File /Users/bill/oss/DefinitelyTyped/node_modules/flatpickr/dist/utils/formatting.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md

https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md says to update package.json but I'm not even sure if it's talking about DefinitelyTyped's package.json or flatpickr's package.json.